#default 공통설정
spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_fetch_size: ${chunkSize:100}
        jdbc.batch_size: ${chunkSize:100}

--- # test 설정
spring:
  config:
    activate:
      on-profile: "test"

  h2:
    console: true

  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: sa
    password:

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "dev"

  jpa:
    hibernate:
      ddl-auto: update
